[package]
name = "zk402-groth16"
version = "0.0.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
ark-bls12-381 = "0.4"
ark-crypto-primitives = { version = "0.4", features = ["crh", "r1cs", "signature"] }
ark-ec = "0.4"
ark-ed-on-bls12-381 = { version = "0.4", features = ["r1cs"] }
ark-ff = "0.4"
ark-groth16 = "0.4"
ark-r1cs-std = "0.4"
ark-relations = "0.4"
ark-serialize = "0.4"
ark-std = "0.4"
rand = "0.8"
sha2 = "0.10"
zeroize = "=1.8.1"
zeroize_derive = "=1.4.2"
